### ISSUE TITLE
How do I install the module via composer?

### ISSUE THREAD

**Issue by cerebrumgit** [magento-hackathon/Hackathon_AddressValidation#23]
How do I install the module via composer?

**Comment by janmartenjongerius** [comment]
@cerebrumgit I'm sorry to say the project currently is not in a functional state. We're working on this, in the few of hours next to our jobs we get. Once the project is stable, we will host it on packagist. There is a real chance we might move this project to a different organisation, because we will split it up in multiple composer packages. If you still want to install it and fiddle around, I suggest you look for a manual on how to install a git repository as a composer repository. See https://github.com/magento-hackathon/Hackathon_AddressValidation/issues/6 on why we want to split it up.

**Comment by cerebrumgit** [comment]
Hello

Thank you for the information

I managed to install as follows module

composer config repositories.hackathon-addressvalidation vcs https://github.com/magento-hackathon/Hackathon_AddressValidation

composer require hackathon/module-address-validation:dev-master

**Comment by janmartenjongerius** [comment]
Hello @cerebrumgit,
You can also add the following to your `composer.json` file and do the same:

``` json
"repositories": [
    {
        "type": "git",
        "url": "git@github.com:magento-hackathon/Hackathon_AddressValidation.git"
    }
]
```

Or use your approach with `vcs` and the HTTPS URL.
